auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka-broker-1:9092
    kafkaConnect:
    - address: http://kafka-connect:8083
      name: kafka-connect
    name: local-dev
    properties: {}
    readOnly: false
    schemaRegistry: http://schema-registry:8081
  - bootstrapServers: 192.168.1.7:9092
    name: HOMELAB
    properties: {}
    readOnly: false
    schemaRegistry: http://192.168.1.7:8081
rbac:
  roles: []
webclient: {}
