version: "3.7"

name: cqrs-demo

services:
  database:
    hostname: database
    image: postgres:14-alpine
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: cqrs-demo
      POSTGRES_USER: cqrs-demo
      POSTGRES_PASSWORD: p@ssw0rd1

volumes:
  database_data:
